// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems/Climber.h"
#include "subsystems/DriveTrain.h"
#include "subsystems/Intake.h"
#include "subsystems/Magazine.h"
#include "subsystems/Shooter.h"

#include "commands/AutoAim.h"
#include "commands/AutonomousCommand.h"
#include "commands/Climb.h"
#include "commands/Drive.h"
#include "commands/HighGear.h"
#include "commands/HoodHighGoal.h"
#include "commands/HoodLowGoal.h"
#include "commands/IntakeDeploy.h"
#include "commands/IntakeRetract.h"
#include "commands/LowGear.h"
#include "commands/ShootHigh.h"
#include "commands/ShootLow.h"
#include <frc/Joystick.h>
#include <frc2/command/button/JoystickButton.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
// The robot's subsystems
Magazine m_magazine;
Climber m_climber;
Shooter m_shooter;
Intake m_intake;
DriveTrain m_driveTrain;


frc::Joystick* getOperator();
frc::Joystick* getDriver();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

private:

    RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// Joysticks
frc::Joystick m_operator{1};
frc::Joystick m_driver{0};

frc::SendableChooser<frc2::Command*> m_chooser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

AutonomousCommand m_autonomousCommand;
    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};